import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from './components/header'
import { Footer } from './components/footer'
import { Navbar } from './components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'teste',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className="flex flex-col min-h-screen">
      <Header />
      <div className="flex justify-center">
          <Navbar />
        </div>
      <div className="flex-grow">{children}</div>
      <Footer />
    </body>
  </html>
  )
}
